<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <ProjectReference Include="..\AutomationPlanner.POC.Core\AutomationPlanner.POC.Core.csproj" />
    <ProjectReference Include="..\AutomationPlanner.POC.Models\AutomationPlanner.POC.Models.csproj" />
  </ItemGroup>
</Project>
